name: MyEvents
main: de.homerbond005.myevents.MyEvents
author: HomerBond005
version: '@PROJECT_VERSION@'
commands:
    event:
        description: Main Command.
        usage: Type /<command> help for help.